### ISSUE TITLE
dragon wings inverted 

### ISSUE THREAD

**Issue by roscio2** [HTTYMD-Team/HTTYMD-Mod#35]
i saw that the nadder and skrill wings are inverted. like they look diferent depending on which position you look.  And the wings are not flaping
![2016-01-11_11 39 16](https://cloud.githubusercontent.com/assets/13804172/12235075/79cd24ec-b858-11e5-8206-6c417ad20e7e.png)
![2016-01-11_11 38 31](https://cloud.githubusercontent.com/assets/13804172/12235079/7cad9cbe-b858-11e5-8a12-d8053e3aa136.png)

**Comment by Spartan322** [comment]
#34
