### ISSUE TITLE
Crash on world start

### ISSUE THREAD

**Issue by KrisJEC** [HTTYMD-Team/HTTYMD-Mod#40]
## Steps to Reproduce
1. Downloaded 1.7.10 (latest) from Forge.  Installer.  
2. Downloaded HTTYD v1.1.0
3. Installed Forge and ran it once.
4. Went to AppData and added the HTTYD jar file to mods folder.
5. Switched Minecraft profile to Forge.
6. Started Forge and checked the mods list for HTTYD. 
7. Created new world.
8. Started said world.
9. Crashed.
10. Made a pastebin here: http://pastebin.com/3qpC0R4m
## Log (if applicable)

See above (#10)
Ran it again, so here is another - http://pastebin.com/5SY3ZBvn
## Images (if applicable)

http://imgur.com/GBuQhSL - Start screen

**Comment by Spartan322** [comment]
The image and the pre-game start steps aren't really needed in this case, the log usually says all that's needed (though I do appreciate that the template was followed, also the pastebin doesn't need to be in the steps)

The options are causing the crash here, 32 is not a native 1.7.10 viewing distance and will usually cause crashes, especially mods, also, #10 has no relation, why did you reference it?

**Comment by Spartan322** [comment]
Also the log tells me nothing about this crash, until I see that the crash is actually the mods fault and not minecraft, it will be closed.

**Comment by KrisJEC** [comment]
#10 was referenced from the original post from Reddit, before I was asked to submit problems here.  For the sake of being thorough and providing all information possible, I included it.  Two separate crashes, two separate pastebins.  I will attempt to reset her viewing distance to something "native".  Any idea what that "native 1.7.10 viewing distance" would be?  Any help you can provide here would be great.  Thanks.

**Comment by Spartan322** [comment]
10 or less is a default viewing distance for 1.7.10, it is common that conversions from 1.8 to 1.7.10 will causes crashes in the options because something about the world only allows a distance of 10 chunks to exist, beyond that and everything is missing and returns a type of "Beyond The Current Scope" problem

**Comment by KrisJEC** [comment]
This is helpful.  Thank you.

Best regards,

Kris Gorden

Operations Manager

Journey Electronics Corp. http://www.journeyelectronics.com/ 

902 Garver Rd.

Monroe, OH 45050

PH          513-539-9836

FAX        513-539-7550

NOTICE:  This email message and all attachments are for the 

sole use of the intended recipient(s) and may contain 

confidential and privileged information.  If you are not the 

intended recipient, you may not read, disseminate, distribute, 

copy or otherwise use this message or its attachments.  If you 

have received this message in error, please contact the sender 

by reply email and destroy all electronic and paper copies of 

the original message. Thank you.
