### ISSUE TITLE
Add dragon calls because sometimes dragons dont warp back to u

### ISSUE THREAD

**Issue by MasterPvpDude** [HTTYMD-Team/HTTYMD-Mod#43]
# Issue Name (don't call it "Please Help" or anything nondescript, this name must be a short description of the issue)

Fully describe your issue here, if its a crash, move to Steps to Reproduce

(If you have no idea what to call a crash call them something like "Crash from <Exception name> at <First thing in stacktrace>", other unnamed issues will be ignored)
## Steps to Reproduce

If you can consistently cause this through certain steps, please provide them
## Log (if applicable)

Either [pastebin](http://www.pastebin.com) or [gist](https://gist.github.com) log (Direct posted logs will be ignored until properly posted, also, DON'T OMIT ANYTHING)

If this is a crash and there is no log, it did not happen
## Images (if applicable)

Please use [imgur](https://imgur.com) (if your issue isn't a crash, but a bug or the like, this more helpful)
## Note (if applicable)

The extra section, do not post "Please fix" or anything of the like

Note: Erase all default stuff, and if a section is unused, please delete it, its otherwise useless, if suggestion or the like, only Issue Name and Description are needed, rest are up to you

WARNING: IF YOU DON'T READ AND FOLLOW THESE DIRECTIONS, YOUR ISSUE WILL BE CLOSED AND IGNORED, WE CAN NOT ACTUALLY HELP IF YOU DON'T LISTEN

**Comment by Spartan322** [comment]
Don't send suggestions to the issue tracker
