### ISSUE TITLE
Mod Crashes Forge says its ERRORED is the mod compatable with MB battle gear???

### ISSUE THREAD

**Issue by NightFuryGaming** [HTTYMD-Team/HTTYMD-Mod#46]
I just added Mine and Blade Battle Gear and from now i cant get in my minecraft modded server i tried redownloading the mod Nothing happend i deleted Mine and Blade battle Gear Nothing happend Forge still Crashes and says that the mod is Errored i cant fix this problem and i need this mod for my roleplay on youtube pls Help when i get rid of the mod it gets into minecraft whats the bug?

**Comment by ZephyraNF** [comment]
Can you send us a crash log so we can take a look?

**Comment by NightFuryGaming** [comment]
yes i can

**Comment by NightFuryGaming** [comment]
[crash-2016-08-08_02.51.34-client.txt](https://github.com/HTTYMD-Team/HTTYMD-Mod/files/405842/crash-2016-08-08_02.51.34-client.txt)

**Comment by ZephyraNF** [comment]
Interesting, i will contact spartain so that he will come and take a look, he will know better then me

**Comment by NightFuryGaming** [comment]
ok

**Comment by NightFuryGaming** [comment]
i need this mod for my roleplay in 2 days

**Comment by Spartan322** [comment]
I'll see what I can find, but next time, use pastebin please.

**Comment by NightFuryGaming** [comment]
ok

**Comment by Spartan322** [comment]
it appears you are suffering from a corrupt version download the latest version and try again.

**Comment by NightFuryGaming** [comment]
i did

**Comment by Spartan322** [comment]
Battlegears2 and HTTYMD seem to be missing parts, try downloading both for the server and client

**Comment by NightFuryGaming** [comment]
but it crashed with MB battle gear

**Comment by NightFuryGaming** [comment]
im downloading battle gear and httymd now

**Comment by Spartan322** [comment]
yeah, all I can say from this log is that both HTTYMD and BG2 are missing important files.

**Comment by NightFuryGaming** [comment]
idk how
BG2 was on latest update

**Comment by NightFuryGaming** [comment]
i didnt know about httymd

**Comment by Spartan322** [comment]
downloaded files are not guaranteed to download 100% correctly (this is why you should try redownloading first), and make sure you are using the latest on both.

**Comment by NightFuryGaming** [comment]
i am
Edit: ok they are in lets see if it works
Edit 2: so far so good
Edit 3: Thank you guys so mutch you saved my youtube roleplay im giving you a shoutout in all my RP vids

**Comment by NightFuryGaming** [comment]
ok they are in lets see if it works

**Comment by NightFuryGaming** [comment]
so far so good

**Comment by NightFuryGaming** [comment]
Thank you guys so mutch you saved my youtube roleplay im giving you a shoutout in all my RP vids

**Comment by Spartan322** [comment]
thanks, I'm gonna mark this an invalid as its not really a problem, and could you also tell people that if you have problems with the mod to first make sure it has a proper view distance setting for 1.7.10 and to make sure the files aren't corrupt by re-downloading all problem mods to make sure before asking about problems. It would probably help a lot to cut down on the more spammy issues.

**Comment by NightFuryGaming** [comment]
i did redownload both mods but it didnt work last time

**Comment by Spartan322** [comment]
you do know we have a httymd discord server btw
