### ISSUE TITLE
STDOUT [com.github.alexthe666.iceandfire.entity.EntityHippogryph:func_70652_k:651]: help

### ISSUE THREAD

**Issue by bzald** [HTTYMD-Team/HTTYMD-Mod#48]
# Issue Name (don't call it "Please Help" or anything nondescript, this name must be a short description of the issue)
Fully describe your issue here, if its a crash, move to Steps to Reproduce

server is getting this issue, STDOUT [com.github.alexthe666.iceandfire.entity.EntityHippogryph:func_70652_k:651]: help

(If you have no idea what to call a crash call them something like "Crash from <Exception name> at <First thing in stacktrace>", other unnamed issues will be ignored)

## Steps to Reproduce

I'm not sure since it is something that is on always and lagging

## Log (if applicable)
Either [pastebin](http://www.pastebin.com) or [gist](https://gist.github.com) log (Direct posted logs will be ignored until properly posted, also, DON'T OMIT ANYTHING)

no crash and that the issue just a really high ram with the above error

If this is a crash and there is no log, it did not happen

## Images (if applicable)
Please use [imgur](https://imgur.com) (if your issue isn't a crash, but a bug or the like, this more helpful)

## Note (if applicable)
The extra section, do not post "Please fix" or anything of the like

Note: Erase all default stuff, and if a section is unused, please delete it, its otherwise useless, if suggestion or the like, only Issue Name and Description are needed, rest are up to you

WARNING: IF YOU DON'T READ AND FOLLOW THESE DIRECTIONS, YOUR ISSUE WILL BE CLOSED AND IGNORED, WE CAN NOT ACTUALLY HELP IF YOU DON'T LISTEN

**Comment by Spartan322** [comment]
Also our mod is not responsible when you are using another mod, clearly this is not our mods fault, don't ask me further on this problem because I will not respond because we are not responsible for it
