### ISSUE TITLE
Survival Inventory Crash

### ISSUE THREAD

**Issue by ZephyraNF** [HTTYMD-Team/HTTYMD-Mod#9]
Might be due to other armor in the inventory, but im not 100% sure

Happens when you are in Survival and open Inventory, may only work if you have armor on and or in your inventory

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 11/2/15 11:20 AM
Description: Rendering entity in world

java.lang.ClassCastException: net.minecraft.item.ItemArmor cannot be cast to com.httymd.item.ItemGlideArmor
    at com.httymd.client.event.PlayerClientHandler.beforeBodyRender(PlayerClientHandler.java:46)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_11_PlayerClientHandler_beforeBodyRender_Pre.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:71)
    at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:158)
    at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:521)
    at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
    at net.minecraft.client.renderer.entity.RenderManager.func_147940_a(RenderManager.java:276)
    at net.minecraft.client.gui.inventory.GuiInventory.func_147046_a(SourceFile:91)
    at net.minecraft.client.gui.inventory.GuiInventory.func_146976_a(SourceFile:60)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
    at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1357)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.httymd.client.event.PlayerClientHandler.beforeBodyRender(PlayerClientHandler.java:46)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_11_PlayerClientHandler_beforeBodyRender_Pre.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:71)
    at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:158)
    at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:521)

-- Entity being rendered --
Details:
    Entity Type: null (net.minecraft.client.entity.EntityClientPlayerMP)
    Entity ID: 305
    Entity Name: CodyMMR
    Entity's Exact location: 5.48, 89.62, 165.17
    Entity's Block location: World: (5,89,165), Chunk: (at 5,5,5 in 0,10; contains blocks 0,0,160 to 15,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Entity's Momentum: 0.00, -0.08, 0.00

-- Renderer details --
Details:
    Assigned renderer: RenderPlayerOF@64f17a8f
    Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Rotation: 0.0
    Delta: 1.0
Stacktrace:
    at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
    at net.minecraft.client.renderer.entity.RenderManager.func_147940_a(RenderManager.java:276)
    at net.minecraft.client.gui.inventory.GuiInventory.func_147046_a(SourceFile:91)
    at net.minecraft.client.gui.inventory.GuiInventory.func_146976_a(SourceFile:60)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
    at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47)

-- Screen render details --
Details:
    Screen name: net.minecraft.client.gui.inventory.GuiInventory
    Mouse location: Scaled: (240, 127). Absolute: (960, 508)
    Screen size: Scaled: (480, 255). Absolute: (1920, 1017). Scale factor of 4

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['CodyMMR'/305, l='MpServer', x=5.48, y=89.62, z=165.17]]
    Chunk stats: MultiplayerChunkCache: 289, 298
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (132,64,256), Chunk: (at 4,4,0 in 8,16; contains blocks 128,0,256 to 143,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 1350889 game time, 821459 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 109 total; [EntityCow['Cow'/0, l='MpServer', x=-57.59, y=81.00, z=97.63], EntityBat['Bat'/1, l='MpServer', x=-55.25, y=29.00, z=133.22], EntityCreeper['Creeper'/2, l='MpServer', x=-55.66, y=41.00, z=128.94], EntitySkeleton['Skeleton'/3, l='MpServer', x=-50.50, y=40.00, z=138.50], EntityBat['Bat'/4, l='MpServer', x=-58.72, y=31.01, z=135.97], EntitySheep['Sheep'/5, l='MpServer', x=-48.94, y=84.00, z=128.13], EntitySheep['Sheep'/6, l='MpServer', x=-52.50, y=72.00, z=160.66], EntitySpider['Spider'/7, l='MpServer', x=-50.84, y=53.00, z=177.63], EntitySpider['Spider'/8, l='MpServer', x=-54.44, y=68.00, z=189.78], EntitySheep['Sheep'/9, l='MpServer', x=-61.63, y=63.00, z=208.47], EntityCow['Cow'/10, l='MpServer', x=-50.47, y=69.00, z=200.66], EntityCreeper['Creeper'/11, l='MpServer', x=-61.31, y=23.00, z=227.47], EntityCow['Cow'/12, l='MpServer', x=-56.16, y=63.00, z=224.94], EntitySquid['Squid'/13, l='MpServer', x=-52.47, y=61.34, z=227.46], EntityCreeper['Creeper'/19, l='MpServer', x=-38.50, y=12.00, z=86.50], EntitySkeleton['Skeleton'/21, l='MpServer', x=-38.47, y=13.00, z=93.03], EntityZombie['Zombie'/20, l='MpServer', x=-39.47, y=12.00, z=86.88], EntityZombie['Zombie'/23, l='MpServer', x=-40.69, y=54.81, z=130.31], EntitySkeleton['Skeleton'/22, l='MpServer', x=-46.50, y=23.00, z=139.50], EntitySheep['Sheep'/25, l='MpServer', x=-51.41, y=67.00, z=150.57], EntitySkeleton['Skeleton'/24, l='MpServer', x=-41.70, y=54.16, z=131.30], EntitySheep['Sheep'/27, l='MpServer', x=-35.53, y=71.00, z=161.34], EntitySheep['Sheep'/26, l='MpServer', x=-33.72, y=95.00, z=150.25], EntitySheep['Sheep'/29, l='MpServer', x=-42.66, y=66.00, z=195.59], EntitySpider['Spider'/28, l='MpServer', x=-34.09, y=23.00, z=205.94], EntitySheep['Sheep'/31, l='MpServer', x=-36.59, y=63.00, z=239.78], EntitySheep['Sheep'/30, l='MpServer', x=-44.53, y=64.00, z=198.59], EntitySheep['Sheep'/34, l='MpServer', x=-26.13, y=77.00, z=227.03], EntitySheep['Sheep'/32, l='MpServer', x=-41.47, y=68.00, z=224.38], EntitySheep['Sheep'/33, l='MpServer', x=-35.44, y=75.00, z=224.44], EntitySkeleton['Skeleton'/39, l='MpServer', x=-24.50, y=50.00, z=95.50], EntityItem['item.item.rottenFlesh'/42, l='MpServer', x=-23.31, y=97.13, z=152.13], EntitySheep['Sheep'/43, l='MpServer', x=-28.13, y=79.00, z=209.53], EntitySheep['Sheep'/40, l='MpServer', x=-28.09, y=79.00, z=101.66], EntityCreeper['Creeper'/41, l='MpServer', x=-26.97, y=65.00, z=121.66], EntitySheep['Sheep'/46, l='MpServer', x=-11.94, y=80.00, z=235.84], EntitySheep['Sheep'/44, l='MpServer', x=-29.97, y=79.00, z=208.06], EntityItem['item.item.rottenFlesh'/45, l='MpServer', x=-29.69, y=77.13, z=221.13], EntityZombie['Zombie'/62, l='MpServer', x=-0.34, y=56.00, z=239.31], EntityZombie['Zombie'/61, l='MpServer', x=-5.88, y=68.00, z=189.44], EntityBat['Bat'/60, l='MpServer', x=2.54, y=47.00, z=190.39], EntityZombie['Zombie'/64, l='MpServer', x=0.47, y=53.00, z=243.91], EntityZombie['Zombie'/65, l='MpServer', x=1.69, y=51.71, z=235.50], EntityClientPlayerMP['CodyMMR'/305, l='MpServer', x=5.48, y=89.62, z=165.17], EntityCreeper['Creeper'/87, l='MpServer', x=15.50, y=16.00, z=127.50], EntityCreeper['Creeper'/93, l='MpServer', x=7.28, y=45.00, z=216.50], EntityZombie['Zombie'/92, l='MpServer', x=15.34, y=49.00, z=207.00], EntityZombie['Zombie'/95, l='MpServer', x=2.00, y=47.00, z=227.44], EntityCreeper['Creeper'/94, l='MpServer', x=7.50, y=45.00, z=220.50], EntitySkeleton['Skeleton'/89, l='MpServer', x=16.00, y=49.00, z=203.22], EntitySkeleton['Skeleton'/88, l='MpServer', x=-1.06, y=58.00, z=168.56], EntityBat['Bat'/91, l='MpServer', x=14.50, y=49.10, z=195.75], EntitySpider['Spider'/90, l='MpServer', x=15.03, y=49.00, z=205.66], EntityZombie['Zombie'/102, l='MpServer', x=25.94, y=18.00, z=143.50], EntityZombie['Zombie'/103, l='MpServer', x=11.91, y=47.00, z=193.41], EntitySpider['Spider'/369, l='MpServer', x=-64.50, y=30.00, z=186.50], EntityZombie['Zombie'/368, l='MpServer', x=-65.50, y=30.00, z=191.50], EntityCow['Cow'/371, l='MpServer', x=-73.13, y=69.00, z=231.66], EntitySkeleton['Skeleton'/370, l='MpServer', x=-70.50, y=30.00, z=196.50], EntityCreeper['Creeper'/110, l='MpServer', x=32.38, y=79.00, z=172.53], EntitySheep['Sheep'/111, l='MpServer', x=37.16, y=90.00, z=170.28], EntitySkeleton['Skeleton'/104, l='MpServer', x=18.50, y=49.00, z=199.13], EntityBat['Bat'/105, l='MpServer', x=23.84, y=21.10, z=225.97], EntityBat['Bat'/119, l='MpServer', x=35.53, y=36.29, z=228.22], EntitySheep['Sheep'/118, l='MpServer', x=44.59, y=84.00, z=208.84], EntityBat['Bat'/117, l='MpServer', x=37.50, y=38.29, z=219.38], EntityBat['Bat'/359, l='MpServer', x=-68.69, y=58.35, z=118.34], EntityBat['Bat'/116, l='MpServer', x=39.69, y=37.00, z=220.16], EntityBat['Bat'/115, l='MpServer', x=34.25, y=35.00, z=228.44], EntityCreeper['Creeper'/114, l='MpServer', x=40.50, y=37.00, z=217.50], EntityItem['item.item.sulphur'/113, l='MpServer', x=47.41, y=26.13, z=217.19], EntityZombie['Zombie'/112, l='MpServer', x=45.50, y=42.00, z=207.50], EntityZombie['Zombie'/364, l='MpServer', x=-66.31, y=40.00, z=147.06], EntitySheep['Sheep'/365, l='MpServer', x=-65.30, y=60.90, z=156.53], EntityZombie['Zombie'/126, l='MpServer', x=58.50, y=40.00, z=224.97], EntityCow['Cow'/366, l='MpServer', x=-71.31, y=92.00, z=144.63], EntityZombie['Zombie'/125, l='MpServer', x=59.50, y=41.00, z=220.97], EntityZombie['Zombie'/367, l='MpServer', x=-65.50, y=30.00, z=188.50], EntitySkeleton['Skeleton'/124, l='MpServer', x=54.50, y=42.00, z=197.50], EntityCow['Cow'/360, l='MpServer', x=-72.50, y=116.00, z=127.38], EntityZombie['Zombie'/362, l='MpServer', x=-67.13, y=30.00, z=157.53], EntityZombie['Zombie'/363, l='MpServer', x=-67.25, y=40.00, z=146.44], EntityBat['Bat'/120, l='MpServer', x=34.53, y=35.00, z=245.25], EntitySheep['Sheep'/137, l='MpServer', x=79.44, y=85.00, z=109.22], EntitySheep['Sheep'/136, l='MpServer', x=78.25, y=85.00, z=111.75], EntitySheep['Sheep'/139, l='MpServer', x=79.41, y=85.00, z=108.09], EntitySheep['Sheep'/138, l='MpServer', x=79.66, y=85.00, z=110.50], EntitySheep['Sheep'/141, l='MpServer', x=79.38, y=85.00, z=112.91], EntitySheep['Sheep'/140, l='MpServer', x=77.09, y=85.00, z=112.91], EntitySkeleton['Skeleton'/143, l='MpServer', x=70.84, y=41.00, z=191.28], EntitySheep['Sheep'/129, l='MpServer', x=78.19, y=85.00, z=108.09], EntitySheep['Sheep'/131, l='MpServer', x=77.09, y=85.00, z=110.47], EntitySheep['Sheep'/130, l='MpServer', x=77.09, y=85.00, z=109.25], EntitySheep['Sheep'/133, l='MpServer', x=78.19, y=85.00, z=110.72], EntitySheep['Sheep'/132, l='MpServer', x=78.28, y=85.00, z=109.19], EntitySheep['Sheep'/135, l='MpServer', x=77.09, y=85.00, z=108.09], EntitySheep['Sheep'/134, l='MpServer', x=77.09, y=85.00, z=111.78], EntitySheep['Sheep'/152, l='MpServer', x=80.50, y=85.00, z=108.09], EntitySheep['Sheep'/153, l='MpServer', x=81.91, y=85.00, z=109.28], EntitySheep['Sheep'/154, l='MpServer', x=80.91, y=85.00, z=111.78], EntitySheep['Sheep'/155, l='MpServer', x=80.75, y=85.00, z=110.50], EntitySheep['Sheep'/156, l='MpServer', x=81.88, y=85.00, z=110.50], EntitySheep['Sheep'/157, l='MpServer', x=80.63, y=85.00, z=109.38], EntitySheep['Sheep'/158, l='MpServer', x=80.41, y=85.00, z=112.91], EntitySheep['Sheep'/159, l='MpServer', x=81.91, y=85.00, z=112.91], EntityCreeper['Creeper'/144, l='MpServer', x=76.50, y=42.00, z=184.50], EntityItem['item.item.bone'/146, l='MpServer', x=68.72, y=63.13, z=196.19], EntitySheep['Sheep'/151, l='MpServer', x=81.81, y=85.00, z=108.09], EntityWitch['Witch'/162, l='MpServer', x=84.13, y=20.00, z=167.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.7.0_75, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 807070968 bytes (769 MB) / 1227239424 bytes (1170 MB) up to 4187619328 bytes (3993 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 Optifine OptiFine_1.7.10_HD_B5 4 mods loaded, 4 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1230} [Forge Mod Loader](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1230} [Minecraft Forge](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    httymd{1.0.0} [How to Train Your Minecraft Dragon](HTTYMD-1.7.10-10.13.2.1230F-1.0R.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Launched Version: 1.7.10-Forge10.13.2.1230
    LWJGL: 2.9.1
    OpenGL: AMD Radeon HD 7600G GL version 4.5.13397 Compatibility Profile Context 15.200.1055.0, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by Spartan322** [comment]
Will be fixed in a few
